#!/bin/bash -ex

ORGA=lopsided
TAR_DATE=${TAR_DATE:-$(date +'%Y.%m')}
ARCH=armv6h

for repo in archlinux-${ARCH} archlinux-${ARCH}:full archlinux-${ARCH}:devel; do
	IFS=: read repo tag <<< $repo
	docker build -f ./Dockerfiles/updates/Dockerfile${tag:+.$tag} -t ${ORGA}/${repo}${tag:+:$tag} ./Dockerfiles/updates
done
